"""add email_change_requests table

Revision ID: 4f79d292f18a
Revises: 5f1a1b1b6ae2
Create Date: 2026-07-23 22:02:57.468360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f79d292f18a'
down_revision = '5f1a1b1b6ae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_change_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('old_email', sa.String(length=255), nullable=False),
    sa.Column('new_email', sa.String(length=255), nullable=False),
    sa.Column('old_email_token_hash', sa.String(length=64), nullable=False),
    sa.Column('new_email_token_hash', sa.String(length=64), nullable=False),
    sa.Column('old_email_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('new_email_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('new_email_token_hash'),
    sa.UniqueConstraint('old_email_token_hash')
    )
    with op.batch_alter_table('email_change_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_change_requests_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_change_requests_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_change_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_change_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_email_change_requests_expires_at'))

    op.drop_table('email_change_requests')
    # ### end Alembic commands ###
