"""Security services (TOTP authenticator-app MFA)."""

from hypatia.services.security.totp import (
    CURRENT_PASSWORD_INCORRECT_MESSAGE,
    TOTP_ALREADY_ENABLED_MESSAGE,
    TOTP_CONFIGURATION_ERROR_MESSAGE,
    TOTP_INVALID_CODE_MESSAGE,
    TOTP_NOT_ENABLED_MESSAGE,
    TOTP_SETUP_CANCELLED_MESSAGE,
    TOTP_SETUP_REQUIRED_MESSAGE,
    TotpCancelSetupResult,
    TotpDisableResult,
    TotpEnableResult,
    TotpSetupResult,
    cancel_totp_setup,
    disable_totp,
    enable_totp,
    setup_totp,
    user_has_totp_enabled,
)
from hypatia.services.security.totp_crypto import (
    TOTP_ENCRYPTION_INVALID_KEY_MESSAGE,
    TOTP_ENCRYPTION_NOT_CONFIGURED_MESSAGE,
    TotpEncryptionError,
    decrypt_totp_secret,
    encrypt_totp_secret,
)
from hypatia.services.security.totp_verify import (
    TotpVerificationResult,
    build_provisioning_uri,
    generate_totp_secret,
    verify_totp_code,
)

__all__ = [
    "CURRENT_PASSWORD_INCORRECT_MESSAGE",
    "TOTP_ALREADY_ENABLED_MESSAGE",
    "TOTP_CONFIGURATION_ERROR_MESSAGE",
    "TOTP_ENCRYPTION_INVALID_KEY_MESSAGE",
    "TOTP_ENCRYPTION_NOT_CONFIGURED_MESSAGE",
    "TOTP_INVALID_CODE_MESSAGE",
    "TOTP_NOT_ENABLED_MESSAGE",
    "TOTP_SETUP_CANCELLED_MESSAGE",
    "TOTP_SETUP_REQUIRED_MESSAGE",
    "TotpCancelSetupResult",
    "TotpDisableResult",
    "TotpEnableResult",
    "TotpEncryptionError",
    "TotpSetupResult",
    "TotpVerificationResult",
    "build_provisioning_uri",
    "cancel_totp_setup",
    "decrypt_totp_secret",
    "disable_totp",
    "enable_totp",
    "encrypt_totp_secret",
    "generate_totp_secret",
    "setup_totp",
    "user_has_totp_enabled",
    "verify_totp_code",
]
