"""Shared authentication constants."""

from __future__ import annotations

ACCOUNT_STATUS_ACTIVE = "active"

EVENT_ACCOUNT_CREATED = "ACCOUNT_CREATED"
EVENT_LOGIN_SUCCESS = "LOGIN_SUCCESS"
EVENT_LOGIN_FAILED = "LOGIN_FAILED"
EVENT_PASSWORD_CHANGED = "PASSWORD_CHANGED"
EVENT_EMAIL_CHANGE_REQUESTED = "EMAIL_CHANGE_REQUESTED"
EVENT_EMAIL_CHANGED = "EMAIL_CHANGED"
EVENT_TOTP_ENABLED = "TOTP_ENABLED"
EVENT_TOTP_DISABLED = "TOTP_DISABLED"

INVALID_CREDENTIALS_MESSAGE = "Invalid email or password"
EMAIL_ALREADY_REGISTERED_MESSAGE = "An account with this email already exists"
UNAUTHENTICATED_MESSAGE = "Authentication required"
