"""Argon2id password hashing and verification."""

from __future__ import annotations

from argon2 import PasswordHasher
from argon2.exceptions import VerificationError, VerifyMismatchError
from argon2.low_level import Type

_hasher = PasswordHasher(type=Type.ID)


def hash_password(plain_password: str) -> str:
    """Return an Argon2id hash for ``plain_password`` (salt generated by argon2)."""
    return _hasher.hash(plain_password)


def verify_password(stored_hash: str, plain_password: str) -> bool:
    """Return True when ``plain_password`` matches ``stored_hash``."""
    try:
        _hasher.verify(stored_hash, plain_password)
        return True
    except (VerifyMismatchError, VerificationError):
        return False


def password_needs_rehash(stored_hash: str) -> bool:
    """Return True when ``stored_hash`` should be replaced with current Argon2id parameters."""
    return _hasher.check_needs_rehash(stored_hash)
