"""Argon2id password hashing and verification."""

from __future__ import annotations

from argon2 import PasswordHasher
from argon2.exceptions import VerificationError, VerifyMismatchError
from argon2.low_level import Type

_hasher = PasswordHasher(type=Type.ID)

# Internal plaintext used only once at module init to build DUMMY_PASSWORD_HASH.
# Not an account credential; never grants access even if a client submits it.
_DUMMY_PASSWORD_PLAINTEXT = "hypatia-dummy-password-not-a-credential"

# One representative Argon2id hash for unknown-email Login timing mitigation.
# Built once per process with the shared PasswordHasher (same parameters as real
# account hashes). Never stored in the database or treated as authentication.
DUMMY_PASSWORD_HASH = _hasher.hash(_DUMMY_PASSWORD_PLAINTEXT)


def hash_password(plain_password: str) -> str:
    """Return an Argon2id hash for ``plain_password`` (salt generated by argon2)."""
    return _hasher.hash(plain_password)


def verify_password(stored_hash: str, plain_password: str) -> bool:
    """Return True when ``plain_password`` matches ``stored_hash``."""
    try:
        _hasher.verify(stored_hash, plain_password)
        return True
    except (VerifyMismatchError, VerificationError):
        return False


def perform_dummy_password_verification(plain_password: str) -> None:
    """Run one Argon2 verify against the in-memory dummy hash; discard the result.

    Used so unknown-email Login performs comparable work to a wrong-password
    attempt. A match against the dummy hash must never authenticate anyone.
    """
    verify_password(DUMMY_PASSWORD_HASH, plain_password)


def password_needs_rehash(stored_hash: str) -> bool:
    """Return True when ``stored_hash`` should be replaced with current Argon2id parameters."""
    return _hasher.check_needs_rehash(stored_hash)
